// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file numen/v1/artifact.proto (package numen.v1, syntax proto3)
/* eslint-disable */

// What a client may ask about the artifacts made from a vault's files.
//
// An artifact is what a model wrote about one file: the text read out of a
// scan, the words heard in a recording, and those words put right. The file
// itself is the person's and is never touched; an artifact stands beside it,
// under a name of the application's own.

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file numen/v1/artifact.proto.
 */
export const file_numen_v1_artifact: GenFile = /*@__PURE__*/
  fileDesc("ChdudW1lbi92MS9hcnRpZmFjdC5wcm90bxIIbnVtZW4udjEiVQoIQXJ0aWZhY3QSDAoEbmFtZRgBIAEoCRIeCgVzdGF0ZRgCIAEoDjIPLm51bWVuLnYxLlN0YXRlEg0KBWVycm9yGAMgASgJEgwKBHNpemUYBCABKAMiJAoUTGlzdEFydGlmYWN0c1JlcXVlc3QSDAoEcGF0aBgBIAEoCSI+ChVMaXN0QXJ0aWZhY3RzUmVzcG9uc2USJQoJYXJ0aWZhY3RzGAEgAygLMhIubnVtZW4udjEuQXJ0aWZhY3QiOgoVQ3JlYXRlQXJ0aWZhY3RSZXF1ZXN0EgwKBHBhdGgYASABKAkSEwoLYXJ0aWZhY3RfaWQYAiABKAkiPgoWQ3JlYXRlQXJ0aWZhY3RSZXNwb25zZRIkCghhcnRpZmFjdBgBIAEoCzISLm51bWVuLnYxLkFydGlmYWN0IjoKFURlbGV0ZUFydGlmYWN0UmVxdWVzdBIMCgRwYXRoGAEgASgJEhMKC2FydGlmYWN0X2lkGAIgASgJIj4KFkRlbGV0ZUFydGlmYWN0UmVzcG9uc2USJAoIYXJ0aWZhY3QYASABKAsyEi5udW1lbi52MS5BcnRpZmFjdCqZAQoFU3RhdGUSFQoRU1RBVEVfVU5TUEVDSUZJRUQQABIOCgpTVEFURV9OT05FEAESEAoMU1RBVEVfUVVFVUVEEAISEQoNU1RBVEVfUlVOTklORxADEhEKDVNUQVRFX1NUT1BQRUQQBBIOCgpTVEFURV9ET05FEAUSDwoLU1RBVEVfRU1QVFkQBhIQCgxTVEFURV9GQUlMRUQQBzKNAgoPQXJ0aWZhY3RTZXJ2aWNlElAKDUxpc3RBcnRpZmFjdHMSHi5udW1lbi52MS5MaXN0QXJ0aWZhY3RzUmVxdWVzdBofLm51bWVuLnYxLkxpc3RBcnRpZmFjdHNSZXNwb25zZRJTCg5DcmVhdGVBcnRpZmFjdBIfLm51bWVuLnYxLkNyZWF0ZUFydGlmYWN0UmVxdWVzdBogLm51bWVuLnYxLkNyZWF0ZUFydGlmYWN0UmVzcG9uc2USUwoORGVsZXRlQXJ0aWZhY3QSHy5udW1lbi52MS5EZWxldGVBcnRpZmFjdFJlcXVlc3QaIC5udW1lbi52MS5EZWxldGVBcnRpZmFjdFJlc3BvbnNlQklaR2dpdGh1Yi5jb20vaml2YS1zdHVkaW8vbnVtZW4vbW9kdWxlcy9saWJzL3Byb3RvY29sL2dlbi9udW1lbi92MTtudW1lbnYxYgZwcm90bzM");

/**
 * An Artifact is one thing a model wrote about one file of the vault.
 *
 * @generated from message numen.v1.Artifact
 */
export type Artifact = Message<"numen.v1.Artifact"> & {
  /**
   * Name is where it stands: the vault, the file it was made from, and the
   * name the store keeps it under.
   *
   *   vaults/{vault}/files/{path}/artifacts/asr.corrected
   *
   * It is answered and never asked with: a request names the file and the
   * artifact of it, and the vault is the one the window is showing.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * State is what has become of it.
   *
   * @generated from field: numen.v1.State state = 2;
   */
  state: State;

  /**
   * Error is what stopped it, and is set when it failed.
   *
   * @generated from field: string error = 3;
   */
  error: string;

  /**
   * Size is how many bytes stand under that name. A file being written is
   * appended to as the work goes, so it keeps its name and grows: how long it
   * now is is what tells a caller that what it already read has moved on.
   *
   * @generated from field: int64 size = 4;
   */
  size: bigint;
};

/**
 * Describes the message numen.v1.Artifact.
 * Use `create(ArtifactSchema)` to create a new message.
 */
export const ArtifactSchema: GenMessage<Artifact> = /*@__PURE__*/
  messageDesc(file_numen_v1_artifact, 0);

/**
 * @generated from message numen.v1.ListArtifactsRequest
 */
export type ListArtifactsRequest = Message<"numen.v1.ListArtifactsRequest"> & {
  /**
   * The file of the vault, as the vault holds it.
   *
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message numen.v1.ListArtifactsRequest.
 * Use `create(ListArtifactsRequestSchema)` to create a new message.
 */
export const ListArtifactsRequestSchema: GenMessage<ListArtifactsRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_artifact, 1);

/**
 * @generated from message numen.v1.ListArtifactsResponse
 */
export type ListArtifactsResponse = Message<"numen.v1.ListArtifactsResponse"> & {
  /**
   * Every artifact this file can carry, whether or not any of it stands. A row
   * is how a client is told that nothing has been made, which is an answer and
   * not an absence.
   *
   * @generated from field: repeated numen.v1.Artifact artifacts = 1;
   */
  artifacts: Artifact[];
};

/**
 * Describes the message numen.v1.ListArtifactsResponse.
 * Use `create(ListArtifactsResponseSchema)` to create a new message.
 */
export const ListArtifactsResponseSchema: GenMessage<ListArtifactsResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_artifact, 2);

/**
 * @generated from message numen.v1.CreateArtifactRequest
 */
export type CreateArtifactRequest = Message<"numen.v1.CreateArtifactRequest"> & {
  /**
   * The file of the vault, as the vault holds it.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * Which artifact of it to make. It is the last part of the artifact's name:
   *
   *   ocr             the text read out of a scan
   *   asr             the words heard in a recording
   *   asr.corrected   those words put right
   *
   * Which model does the work follows from the file, and is not asked for
   * here.
   *
   * @generated from field: string artifact_id = 2;
   */
  artifactId: string;
};

/**
 * Describes the message numen.v1.CreateArtifactRequest.
 * Use `create(CreateArtifactRequestSchema)` to create a new message.
 */
export const CreateArtifactRequestSchema: GenMessage<CreateArtifactRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_artifact, 3);

/**
 * @generated from message numen.v1.CreateArtifactResponse
 */
export type CreateArtifactResponse = Message<"numen.v1.CreateArtifactResponse"> & {
  /**
   * @generated from field: numen.v1.Artifact artifact = 1;
   */
  artifact?: Artifact | undefined;
};

/**
 * Describes the message numen.v1.CreateArtifactResponse.
 * Use `create(CreateArtifactResponseSchema)` to create a new message.
 */
export const CreateArtifactResponseSchema: GenMessage<CreateArtifactResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_artifact, 4);

/**
 * @generated from message numen.v1.DeleteArtifactRequest
 */
export type DeleteArtifactRequest = Message<"numen.v1.DeleteArtifactRequest"> & {
  /**
   * The file of the vault, as the vault holds it.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * Which artifact of it to take away. Only `asr` is taken away here: it is
   * everything listening to a recording produced, and the words put right go
   * with it.
   *
   * @generated from field: string artifact_id = 2;
   */
  artifactId: string;
};

/**
 * Describes the message numen.v1.DeleteArtifactRequest.
 * Use `create(DeleteArtifactRequestSchema)` to create a new message.
 */
export const DeleteArtifactRequestSchema: GenMessage<DeleteArtifactRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_artifact, 5);

/**
 * @generated from message numen.v1.DeleteArtifactResponse
 */
export type DeleteArtifactResponse = Message<"numen.v1.DeleteArtifactResponse"> & {
  /**
   * The artifact as it now stands, which is nothing.
   *
   * @generated from field: numen.v1.Artifact artifact = 1;
   */
  artifact?: Artifact | undefined;
};

/**
 * Describes the message numen.v1.DeleteArtifactResponse.
 * Use `create(DeleteArtifactResponseSchema)` to create a new message.
 */
export const DeleteArtifactResponseSchema: GenMessage<DeleteArtifactResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_artifact, 6);

/**
 * State is what has become of one artifact.
 *
 * @generated from enum numen.v1.State
 */
export enum State {
  /**
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Nothing has been made. The file carries this artifact and none of it
   * stands.
   *
   * @generated from enum value: STATE_NONE = 1;
   */
  NONE = 1,

  /**
   * A run over this file is waiting behind the one going now.
   *
   * @generated from enum value: STATE_QUEUED = 2;
   */
  QUEUED = 2,

  /**
   * A run is writing it now.
   *
   * @generated from enum value: STATE_RUNNING = 3;
   */
  RUNNING = 3,

  /**
   * A run wrote part of it and is not holding it: it stopped, and what it
   * reached is on disk. Asking again begins afresh.
   *
   * @generated from enum value: STATE_STOPPED = 4;
   */
  STOPPED = 4,

  /**
   * The whole of it stands.
   *
   * @generated from enum value: STATE_DONE = 5;
   */
  DONE = 5,

  /**
   * A run read the file and found nothing to write down — a recording holding
   * no speech. Asking again reads the same file and finds the same, so what it
   * found is kept and answered instead.
   *
   * @generated from enum value: STATE_EMPTY = 6;
   */
  EMPTY = 6,

  /**
   * A run could not read the file at all, and error says what it said about it.
   * Taking the artifact away is how a person asks for the file to be tried
   * afresh.
   *
   * @generated from enum value: STATE_FAILED = 7;
   */
  FAILED = 7,
}

/**
 * Describes the enum numen.v1.State.
 */
export const StateSchema: GenEnum<State> = /*@__PURE__*/
  enumDesc(file_numen_v1_artifact, 0);

/**
 * ArtifactService answers what has been made from a file of the vault, makes
 * one, and takes one away.
 *
 * @generated from service numen.v1.ArtifactService
 */
export const ArtifactService: GenService<{
  /**
   * ListArtifacts is every artifact a file can carry and what has become of
   * each. A file whose kind carries none is answered with none.
   *
   * It is asked before anything is offered over a file: whether a book has been
   * read is a question about the book, and the only other way to ask it is to
   * ask for the book to be read again and be refused.
   *
   * @generated from rpc numen.v1.ArtifactService.ListArtifacts
   */
  listArtifacts: {
    methodKind: "unary";
    input: typeof ListArtifactsRequestSchema;
    output: typeof ListArtifactsResponseSchema;
  },
  /**
   * CreateArtifact asks for one to be made, and answers at once with what
   * became of the ask. The work carries on behind the answer, and how far it
   * gets is in the list of what is being done.
   *
   * A file already carrying the artifact is left alone and answered with what
   * stands. A file a person named is never turned away for want of a turn: it
   * waits in line and is taken up before anything the vault set itself.
   *
   * @generated from rpc numen.v1.ArtifactService.CreateArtifact
   */
  createArtifact: {
    methodKind: "unary";
    input: typeof CreateArtifactRequestSchema;
    output: typeof CreateArtifactResponseSchema;
  },
  /**
   * DeleteArtifact takes one away, with everything cut from it. The file stands
   * as it did before anything was made from it, and it is offered again.
   *
   * @generated from rpc numen.v1.ArtifactService.DeleteArtifact
   */
  deleteArtifact: {
    methodKind: "unary";
    input: typeof DeleteArtifactRequestSchema;
    output: typeof DeleteArtifactResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_numen_v1_artifact, 0);

