// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file numen/v1/review.proto (package numen.v1, syntax proto3)
/* eslint-disable */

// What a client running a person's cards may ask.
//
// Review is an application of its own, beside the editor and over the same
// core, so this service stands beside the editor's and shares nothing with it.
// It reaches every vault the installation knows, because what a person owes
// today is owed across all of them.
//
// A card is laid out here, unlike the cards service, which hands a face over as
// it was written: what a person is shown is the face filled with one card's
// values, and nothing above this has the two halves to fill it with.

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file numen/v1/review.proto.
 */
export const file_numen_v1_review: GenFile = /*@__PURE__*/
  fileDesc("ChVudW1lbi92MS9yZXZpZXcucHJvdG8SCG51bWVuLnYxIpcBCgpWYXVsdE93aW5nEhAKCHZhdWx0X2lkGAEgASgJEgwKBG5hbWUYAiABKAkSDAoEcGF0aBgDIAEoCRINCgVmYWNlcxgEIAEoBRILCgNkdWUYBSABKAUSCwoDbmV3GAYgASgFEiIKBWRlY2tzGAcgAygLMhMubnVtZW4udjEuRGVja093aW5nEg4KBnVucmVhZBgIIAEoCSJCCglEZWNrT3dpbmcSDAoEZGVjaxgBIAEoCRINCgVmYWNlcxgCIAEoBRILCgNkdWUYAyABKAUSCwoDbmV3GAQgASgFIkAKBUFoZWFkEg0KBWFnYWluGAEgASgDEgwKBGhhcmQYAiABKAMSDAoEZ29vZBgDIAEoAxIMCgRlYXN5GAQgASgDIqsBCgVBc2tlZBIMCgRkZWNrGAEgASgJEg8KB3NlY3Rpb24YAiABKAkSDAoEY2FyZBgDIAEoCRIMCgRmYWNlGAQgASgJEg8KB2hlYWRpbmcYBSABKAkSDQoFZnJvbnQYBiABKAkSDAoEYmFjaxgHIAEoCRIMCgRzZWVuGAggASgIEgsKA2R1ZRgJIAEoCRIeCgVhaGVhZBgKIAEoCzIPLm51bWVuLnYxLkFoZWFkIg4KDE93aW5nUmVxdWVzdCI1Cg1Pd2luZ1Jlc3BvbnNlEiQKBnZhdWx0cxgBIAMoCzIULm51bWVuLnYxLlZhdWx0T3dpbmciLgoMU3RhcnRSZXF1ZXN0EhAKCHZhdWx0X2lkGAEgASgJEgwKBGRlY2sYAiABKAkiYAoNU3RhcnRSZXNwb25zZRILCgNydW4YASABKAkSHgoFYXNrZWQYAiADKAsyDy5udW1lbi52MS5Bc2tlZBIRCgl1bndyaXR0ZW4YAyADKAkSDwoHc2tpcHBlZBgEIAEoBSJ9Cg1BbnN3ZXJSZXF1ZXN0EhAKCHZhdWx0X2lkGAEgASgJEgsKA3J1bhgCIAEoCRIMCgRjYXJkGAMgASgJEgwKBGZhY2UYBCABKAkSIAoGcmF0aW5nGAUgASgOMhAubnVtZW4udjEuUmF0aW5nEg8KB3Rvb2tfbXMYBiABKAMiIAoOQW5zd2VyUmVzcG9uc2USDgoGYW5zd2VyGAEgASgJIkAKD1Rha2VCYWNrUmVxdWVzdBIQCgh2YXVsdF9pZBgBIAEoCRILCgNydW4YAiABKAkSDgoGYW5zd2VyGAMgASgJIhIKEFRha2VCYWNrUmVzcG9uc2UqZQoGUmF0aW5nEhYKElJBVElOR19VTlNQRUNJRklFRBAAEhAKDFJBVElOR19BR0FJThABEg8KC1JBVElOR19IQVJEEAISDwoLUkFUSU5HX0dPT0QQAxIPCgtSQVRJTkdfRUFTWRAEMoMCCg1SZXZpZXdTZXJ2aWNlEjgKBU93aW5nEhYubnVtZW4udjEuT3dpbmdSZXF1ZXN0GhcubnVtZW4udjEuT3dpbmdSZXNwb25zZRI4CgVTdGFydBIWLm51bWVuLnYxLlN0YXJ0UmVxdWVzdBoXLm51bWVuLnYxLlN0YXJ0UmVzcG9uc2USOwoGQW5zd2VyEhcubnVtZW4udjEuQW5zd2VyUmVxdWVzdBoYLm51bWVuLnYxLkFuc3dlclJlc3BvbnNlEkEKCFRha2VCYWNrEhkubnVtZW4udjEuVGFrZUJhY2tSZXF1ZXN0GhoubnVtZW4udjEuVGFrZUJhY2tSZXNwb25zZUJJWkdnaXRodWIuY29tL2ppdmEtc3R1ZGlvL251bWVuL21vZHVsZXMvbGlicy9wcm90b2NvbC9nZW4vbnVtZW4vdjE7bnVtZW52MWIGcHJvdG8z");

/**
 * VaultOwing is one vault, and what its cards come to today.
 *
 * @generated from message numen.v1.VaultOwing
 */
export type VaultOwing = Message<"numen.v1.VaultOwing"> & {
  /**
   * @generated from field: string vault_id = 1;
   */
  vaultId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string path = 3;
   */
  path: string;

  /**
   * Faces is every card the vault holds, counted once for each face it is shown
   * through. Due is what was answered before and is owed today; New is what
   * nobody has answered.
   *
   * @generated from field: int32 faces = 4;
   */
  faces: number;

  /**
   * @generated from field: int32 due = 5;
   */
  due: number;

  /**
   * @generated from field: int32 new = 6;
   */
  new: number;

  /**
   * Decks is the same three numbers for each deck, by the path of its file.
   *
   * @generated from field: repeated numen.v1.DeckOwing decks = 7;
   */
  decks: DeckOwing[];

  /**
   * Set when the vault could not be counted: it has never been read by the
   * editor, or its files could not be reached. The three numbers are then zero
   * and this says why, in the person's own words.
   *
   * @generated from field: string unread = 8;
   */
  unread: string;
};

/**
 * Describes the message numen.v1.VaultOwing.
 * Use `create(VaultOwingSchema)` to create a new message.
 */
export const VaultOwingSchema: GenMessage<VaultOwing> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 0);

/**
 * @generated from message numen.v1.DeckOwing
 */
export type DeckOwing = Message<"numen.v1.DeckOwing"> & {
  /**
   * @generated from field: string deck = 1;
   */
  deck: string;

  /**
   * @generated from field: int32 faces = 2;
   */
  faces: number;

  /**
   * @generated from field: int32 due = 3;
   */
  due: number;

  /**
   * @generated from field: int32 new = 4;
   */
  new: number;
};

/**
 * Describes the message numen.v1.DeckOwing.
 * Use `create(DeckOwingSchema)` to create a new message.
 */
export const DeckOwingSchema: GenMessage<DeckOwing> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 1);

/**
 * Ahead is how long each of the four answers would leave this card, in seconds
 * from the moment it was asked. A person choosing between them is choosing
 * between these.
 *
 * @generated from message numen.v1.Ahead
 */
export type Ahead = Message<"numen.v1.Ahead"> & {
  /**
   * @generated from field: int64 again = 1;
   */
  again: bigint;

  /**
   * @generated from field: int64 hard = 2;
   */
  hard: bigint;

  /**
   * @generated from field: int64 good = 3;
   */
  good: bigint;

  /**
   * @generated from field: int64 easy = 4;
   */
  easy: bigint;
};

/**
 * Describes the message numen.v1.Ahead.
 * Use `create(AheadSchema)` to create a new message.
 */
export const AheadSchema: GenMessage<Ahead> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 2);

/**
 * Asked is one card face as it is put to a person.
 *
 * @generated from message numen.v1.Asked
 */
export type Asked = Message<"numen.v1.Asked"> & {
  /**
   * Deck is the path of the file the card stands in, and section the name of
   * the section it stands under. A card standing before the first section
   * carries none.
   *
   * @generated from field: string deck = 1;
   */
  deck: string;

  /**
   * @generated from field: string section = 2;
   */
  section: string;

  /**
   * Card is the mark the card is known by, and face the name of the face it is
   * shown through. The two together are what an answer is recorded against.
   *
   * @generated from field: string card = 3;
   */
  card: string;

  /**
   * @generated from field: string face = 4;
   */
  face: string;

  /**
   * Heading is what the card's heading shows, which is the first line of its
   * first field.
   *
   * @generated from field: string heading = 5;
   */
  heading: string;

  /**
   * Front and back are the face laid out with this card's values, as HTML.
   *
   * @generated from field: string front = 6;
   */
  front: string;

  /**
   * @generated from field: string back = 7;
   */
  back: string;

  /**
   * Seen is false for a card nobody has answered, which is what a person means
   * by a new card. Due is when it comes round, and stands only where it has
   * been answered.
   *
   * @generated from field: bool seen = 8;
   */
  seen: boolean;

  /**
   * @generated from field: string due = 9;
   */
  due: string;

  /**
   * Where each of the four would leave it.
   *
   * @generated from field: numen.v1.Ahead ahead = 10;
   */
  ahead?: Ahead | undefined;
};

/**
 * Describes the message numen.v1.Asked.
 * Use `create(AskedSchema)` to create a new message.
 */
export const AskedSchema: GenMessage<Asked> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 3);

/**
 * @generated from message numen.v1.OwingRequest
 */
export type OwingRequest = Message<"numen.v1.OwingRequest"> & {
};

/**
 * Describes the message numen.v1.OwingRequest.
 * Use `create(OwingRequestSchema)` to create a new message.
 */
export const OwingRequestSchema: GenMessage<OwingRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 4);

/**
 * @generated from message numen.v1.OwingResponse
 */
export type OwingResponse = Message<"numen.v1.OwingResponse"> & {
  /**
   * @generated from field: repeated numen.v1.VaultOwing vaults = 1;
   */
  vaults: VaultOwing[];
};

/**
 * Describes the message numen.v1.OwingResponse.
 * Use `create(OwingResponseSchema)` to create a new message.
 */
export const OwingResponseSchema: GenMessage<OwingResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 5);

/**
 * @generated from message numen.v1.StartRequest
 */
export type StartRequest = Message<"numen.v1.StartRequest"> & {
  /**
   * @generated from field: string vault_id = 1;
   */
  vaultId: string;

  /**
   * Deck is the path of one deck, or empty for every deck the vault holds.
   *
   * @generated from field: string deck = 2;
   */
  deck: string;
};

/**
 * Describes the message numen.v1.StartRequest.
 * Use `create(StartRequestSchema)` to create a new message.
 */
export const StartRequestSchema: GenMessage<StartRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 6);

/**
 * @generated from message numen.v1.StartResponse
 */
export type StartResponse = Message<"numen.v1.StartResponse"> & {
  /**
   * Run is what an answer given in this sitting is written to, and it is what
   * an Answer names.
   *
   * @generated from field: string run = 1;
   */
  run: string;

  /**
   * @generated from field: repeated numen.v1.Asked asked = 2;
   */
  asked: Asked[];

  /**
   * Unwritten are the decks holding a card with no mark that could not be given
   * one. Their cards are not in this sitting and are asked for at the next.
   *
   * @generated from field: repeated string unwritten = 3;
   */
  unwritten: string[];

  /**
   * Skipped is how many lines of the vault's answers could not be read: a run
   * that stopped partway, or a line of a version this build does not know.
   *
   * @generated from field: int32 skipped = 4;
   */
  skipped: number;
};

/**
 * Describes the message numen.v1.StartResponse.
 * Use `create(StartResponseSchema)` to create a new message.
 */
export const StartResponseSchema: GenMessage<StartResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 7);

/**
 * @generated from message numen.v1.AnswerRequest
 */
export type AnswerRequest = Message<"numen.v1.AnswerRequest"> & {
  /**
   * @generated from field: string vault_id = 1;
   */
  vaultId: string;

  /**
   * @generated from field: string run = 2;
   */
  run: string;

  /**
   * @generated from field: string card = 3;
   */
  card: string;

  /**
   * @generated from field: string face = 4;
   */
  face: string;

  /**
   * @generated from field: numen.v1.Rating rating = 5;
   */
  rating: Rating;

  /**
   * Took is how long the card stood on the screen, in milliseconds. It is the
   * one thing about an answer that cannot be measured later.
   *
   * @generated from field: int64 took_ms = 6;
   */
  tookMs: bigint;
};

/**
 * Describes the message numen.v1.AnswerRequest.
 * Use `create(AnswerRequestSchema)` to create a new message.
 */
export const AnswerRequestSchema: GenMessage<AnswerRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 8);

/**
 * @generated from message numen.v1.AnswerResponse
 */
export type AnswerResponse = Message<"numen.v1.AnswerResponse"> & {
  /**
   * Answer is the identifier of the line written, which is what taking it back
   * names.
   *
   * @generated from field: string answer = 1;
   */
  answer: string;
};

/**
 * Describes the message numen.v1.AnswerResponse.
 * Use `create(AnswerResponseSchema)` to create a new message.
 */
export const AnswerResponseSchema: GenMessage<AnswerResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 9);

/**
 * @generated from message numen.v1.TakeBackRequest
 */
export type TakeBackRequest = Message<"numen.v1.TakeBackRequest"> & {
  /**
   * @generated from field: string vault_id = 1;
   */
  vaultId: string;

  /**
   * @generated from field: string run = 2;
   */
  run: string;

  /**
   * Answer is the identifier a previous Answer came back with.
   *
   * @generated from field: string answer = 3;
   */
  answer: string;
};

/**
 * Describes the message numen.v1.TakeBackRequest.
 * Use `create(TakeBackRequestSchema)` to create a new message.
 */
export const TakeBackRequestSchema: GenMessage<TakeBackRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 10);

/**
 * @generated from message numen.v1.TakeBackResponse
 */
export type TakeBackResponse = Message<"numen.v1.TakeBackResponse"> & {
};

/**
 * Describes the message numen.v1.TakeBackResponse.
 * Use `create(TakeBackResponseSchema)` to create a new message.
 */
export const TakeBackResponseSchema: GenMessage<TakeBackResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_review, 11);

/**
 * Rating is how well a card came back. A person says which of the four, and
 * nothing decides it for them.
 *
 * @generated from enum numen.v1.Rating
 */
export enum Rating {
  /**
   * @generated from enum value: RATING_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * RATING_AGAIN is a card that did not come back at all.
   *
   * @generated from enum value: RATING_AGAIN = 1;
   */
  AGAIN = 1,

  /**
   * RATING_HARD is a card that came back, slowly and with effort.
   *
   * @generated from enum value: RATING_HARD = 2;
   */
  HARD = 2,

  /**
   * RATING_GOOD is a card that came back.
   *
   * @generated from enum value: RATING_GOOD = 3;
   */
  GOOD = 3,

  /**
   * RATING_EASY is a card that came back with none.
   *
   * @generated from enum value: RATING_EASY = 4;
   */
  EASY = 4,
}

/**
 * Describes the enum numen.v1.Rating.
 */
export const RatingSchema: GenEnum<Rating> = /*@__PURE__*/
  enumDesc(file_numen_v1_review, 0);

/**
 * ReviewService is the front door, a session, and the answers given in it.
 *
 * @generated from service numen.v1.ReviewService
 */
export const ReviewService: GenService<{
  /**
   * Owing is what every vault the installation knows comes to today: how much
   * it holds, how much is due, and how much has never been asked. It is what
   * the application opens on.
   *
   * A vault the index does not carry yet is listed with nothing counted and
   * says so: the list of its decks is the index's answer, and this application
   * builds none.
   *
   * @generated from rpc numen.v1.ReviewService.Owing
   */
  owing: {
    methodKind: "unary";
    input: typeof OwingRequestSchema;
    output: typeof OwingResponseSchema;
  },
  /**
   * Start opens a run and hands over what to ask, in order. A run writes one
   * file of its own in the vault and nothing else ever appends to it.
   *
   * Naming a deck asks that deck alone. Naming none asks the whole vault, which
   * is the ordinary way to sit down to this.
   *
   * @generated from rpc numen.v1.ReviewService.Start
   */
  start: {
    methodKind: "unary";
    input: typeof StartRequestSchema;
    output: typeof StartResponseSchema;
  },
  /**
   * Answer writes down how a card came back. What comes back is the identifier
   * of the line, which is what taking that answer back names.
   *
   * @generated from rpc numen.v1.ReviewService.Answer
   */
  answer: {
    methodKind: "unary";
    input: typeof AnswerRequestSchema;
    output: typeof AnswerResponseSchema;
  },
  /**
   * TakeBack writes down that an answer was taken back. Both lines stay in the
   * file: nothing in a log is ever rewritten or removed.
   *
   * @generated from rpc numen.v1.ReviewService.TakeBack
   */
  takeBack: {
    methodKind: "unary";
    input: typeof TakeBackRequestSchema;
    output: typeof TakeBackResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_numen_v1_review, 0);

