// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file numen/v1/settings.proto (package numen.v1, syntax proto3)
/* eslint-disable */

// What a client may ask about the file a person configures this installation
// in.
//
// The settings belong to the installation and not to a vault: the same file
// answers whichever vault a window is showing, and every window reads it.

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Refusal } from "./vault_pb.js";
import { file_numen_v1_vault } from "./vault_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file numen/v1/settings.proto.
 */
export const file_numen_v1_settings: GenFile = /*@__PURE__*/
  fileDesc("ChdudW1lbi92MS9zZXR0aW5ncy5wcm90bxIIbnVtZW4udjEiEQoPU2V0dGluZ3NSZXF1ZXN0IlIKEFNldHRpbmdzUmVzcG9uc2USDwoHd3JpdHRlbhgBIAEoCRIMCgRwYXRoGAIgASgJEh8KBm1vZGVscxgDIAMoCzIPLm51bWVuLnYxLk1vZGVsIqIBCgVNb2RlbBIQCghuYW1lZF9hdBgBIAMoCRIMCgRuYW1lGAIgASgJEg0KBXRpdGxlGAMgASgJEg0KBXNoZWxmGAQgASgJEhIKCmJ5X2RlZmF1bHQYBSABKAgSIQoGd3JpdGVzGAYgAygLMhEubnVtZW4udjEuU2V0dGluZxIkCghwcmVzZW5jZRgHIAEoDjISLm51bWVuLnYxLlByZXNlbmNlIiQKB1NldHRpbmcSCgoCYXQYASADKAkSDQoFdmFsdWUYAiABKAkiPAoVQ2hvb3NlU2V0dGluZ3NSZXF1ZXN0EiMKCHNldHRpbmdzGAEgAygLMhEubnVtZW4udjEuU2V0dGluZyIYChZDaG9vc2VTZXR0aW5nc1Jlc3BvbnNlIhUKE1NldHRpbmdzRmlsZVJlcXVlc3QiNQoUU2V0dGluZ3NGaWxlUmVzcG9uc2USDwoHd3JpdHRlbhgBIAEoCRIMCgRwYXRoGAIgASgJIkcKGFdyaXRlU2V0dGluZ3NGaWxlUmVxdWVzdBIPCgd3cml0dGVuGAEgASgJEhEKBHNlZW4YAiABKAlIAIgBAUIHCgVfc2VlbiJfChlXcml0ZVNldHRpbmdzRmlsZVJlc3BvbnNlEicKB3JlZnVzYWwYAiABKA4yES5udW1lbi52MS5SZWZ1c2FsSACIAQFCCgoIX3JlZnVzYWxKBAgBEAJSB2NoYW5nZWQqcwoIUHJlc2VuY2USGAoUUFJFU0VOQ0VfVU5TUEVDSUZJRUQQABIUChBQUkVTRU5DRV9QUkVTRU5UEAESGAoUUFJFU0VOQ0VfTk9UX0ZFVENIRUQQAhIdChlQUkVTRU5DRV9OT1RISU5HX1RPX0ZFVENIEAMy1gIKD1NldHRpbmdzU2VydmljZRJBCghTZXR0aW5ncxIZLm51bWVuLnYxLlNldHRpbmdzUmVxdWVzdBoaLm51bWVuLnYxLlNldHRpbmdzUmVzcG9uc2USUwoOQ2hvb3NlU2V0dGluZ3MSHy5udW1lbi52MS5DaG9vc2VTZXR0aW5nc1JlcXVlc3QaIC5udW1lbi52MS5DaG9vc2VTZXR0aW5nc1Jlc3BvbnNlEk0KDFNldHRpbmdzRmlsZRIdLm51bWVuLnYxLlNldHRpbmdzRmlsZVJlcXVlc3QaHi5udW1lbi52MS5TZXR0aW5nc0ZpbGVSZXNwb25zZRJcChFXcml0ZVNldHRpbmdzRmlsZRIiLm51bWVuLnYxLldyaXRlU2V0dGluZ3NGaWxlUmVxdWVzdBojLm51bWVuLnYxLldyaXRlU2V0dGluZ3NGaWxlUmVzcG9uc2VCSVpHZ2l0aHViLmNvbS9qaXZhLXN0dWRpby9udW1lbi9tb2R1bGVzL2xpYnMvcHJvdG9jb2wvZ2VuL251bWVuL3YxO251bWVudjFiBnByb3RvMw", [file_numen_v1_vault]);

/**
 * @generated from message numen.v1.SettingsRequest
 */
export type SettingsRequest = Message<"numen.v1.SettingsRequest"> & {
};

/**
 * Describes the message numen.v1.SettingsRequest.
 * Use `create(SettingsRequestSchema)` to create a new message.
 */
export const SettingsRequestSchema: GenMessage<SettingsRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 0);

/**
 * @generated from message numen.v1.SettingsResponse
 */
export type SettingsResponse = Message<"numen.v1.SettingsResponse"> & {
  /**
   * Every setting as it stands, as JSON: what the file says, and what an
   * installation nobody has configured does under everything it does not.
   *
   * @generated from field: string written = 1;
   */
  written: string;

  /**
   * The file itself, absolute on this machine.
   *
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * The models the settings that name one can be set to.
   *
   * @generated from field: repeated numen.v1.Model models = 3;
   */
  models: Model[];
};

/**
 * Describes the message numen.v1.SettingsResponse.
 * Use `create(SettingsResponseSchema)` to create a new message.
 */
export const SettingsResponseSchema: GenMessage<SettingsResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 1);

/**
 * Model is one model a setting that names a model can be set to.
 *
 * @generated from message numen.v1.Model
 */
export type Model = Message<"numen.v1.Model"> & {
  /**
   * The setting the model is read from, as a path through the file. The model
   * in force is the one whose name stands there.
   *
   * @generated from field: repeated string named_at = 1;
   */
  namedAt: string[];

  /**
   * What stands there while this model is the one in force.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * What is drawn on the row, and the shelf the rows around it stand under.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string shelf = 4;
   */
  shelf: string;

  /**
   * Set on the model an installation nobody has configured runs on.
   *
   * @generated from field: bool by_default = 5;
   */
  byDefault: boolean;

  /**
   * What choosing it writes. One model is several keys where the model decides
   * more than its own name.
   *
   * @generated from field: repeated numen.v1.Setting writes = 6;
   */
  writes: Setting[];

  /**
   * What this model's files are on this machine.
   *
   * @generated from field: numen.v1.Presence presence = 7;
   */
  presence: Presence;
};

/**
 * Describes the message numen.v1.Model.
 * Use `create(ModelSchema)` to create a new message.
 */
export const ModelSchema: GenMessage<Model> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 2);

/**
 * Setting is one setting of the file and what to put there.
 *
 * @generated from message numen.v1.Setting
 */
export type Setting = Message<"numen.v1.Setting"> & {
  /**
   * The setting, as a path through the file.
   *
   * @generated from field: repeated string at = 1;
   */
  at: string[];

  /**
   * What to write there, as JSON. A value the settings cannot be read out of
   * again is refused, and the file is left as it was.
   *
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message numen.v1.Setting.
 * Use `create(SettingSchema)` to create a new message.
 */
export const SettingSchema: GenMessage<Setting> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 3);

/**
 * @generated from message numen.v1.ChooseSettingsRequest
 */
export type ChooseSettingsRequest = Message<"numen.v1.ChooseSettingsRequest"> & {
  /**
   * The settings to write. They are written together, or none of them is.
   *
   * @generated from field: repeated numen.v1.Setting settings = 1;
   */
  settings: Setting[];
};

/**
 * Describes the message numen.v1.ChooseSettingsRequest.
 * Use `create(ChooseSettingsRequestSchema)` to create a new message.
 */
export const ChooseSettingsRequestSchema: GenMessage<ChooseSettingsRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 4);

/**
 * @generated from message numen.v1.ChooseSettingsResponse
 */
export type ChooseSettingsResponse = Message<"numen.v1.ChooseSettingsResponse"> & {
};

/**
 * Describes the message numen.v1.ChooseSettingsResponse.
 * Use `create(ChooseSettingsResponseSchema)` to create a new message.
 */
export const ChooseSettingsResponseSchema: GenMessage<ChooseSettingsResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 5);

/**
 * @generated from message numen.v1.SettingsFileRequest
 */
export type SettingsFileRequest = Message<"numen.v1.SettingsFileRequest"> & {
};

/**
 * Describes the message numen.v1.SettingsFileRequest.
 * Use `create(SettingsFileRequestSchema)` to create a new message.
 */
export const SettingsFileRequestSchema: GenMessage<SettingsFileRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 6);

/**
 * @generated from message numen.v1.SettingsFileResponse
 */
export type SettingsFileResponse = Message<"numen.v1.SettingsFileResponse"> & {
  /**
   * The file as its person wrote it. A file that is not there is an empty
   * object, which is what an installation nobody has configured runs on.
   *
   * @generated from field: string written = 1;
   */
  written: string;

  /**
   * The file itself, absolute on this machine.
   *
   * @generated from field: string path = 2;
   */
  path: string;
};

/**
 * Describes the message numen.v1.SettingsFileResponse.
 * Use `create(SettingsFileResponseSchema)` to create a new message.
 */
export const SettingsFileResponseSchema: GenMessage<SettingsFileResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 7);

/**
 * @generated from message numen.v1.WriteSettingsFileRequest
 */
export type WriteSettingsFileRequest = Message<"numen.v1.WriteSettingsFileRequest"> & {
  /**
   * What is to stand in the file, written as it was typed.
   *
   * @generated from field: string written = 1;
   */
  written: string;

  /**
   * The file as this caller last read it. Absent for a write that lands on
   * whatever the file now holds.
   *
   * @generated from field: optional string seen = 2;
   */
  seen?: string | undefined;
};

/**
 * Describes the message numen.v1.WriteSettingsFileRequest.
 * Use `create(WriteSettingsFileRequestSchema)` to create a new message.
 */
export const WriteSettingsFileRequestSchema: GenMessage<WriteSettingsFileRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 8);

/**
 * @generated from message numen.v1.WriteSettingsFileResponse
 */
export type WriteSettingsFileResponse = Message<"numen.v1.WriteSettingsFileResponse"> & {
  /**
   * Set when nothing was written, and why. A file holding bytes this caller
   * has not read is REFUSAL_STALE, and the person chooses what happens to
   * their text.
   *
   * @generated from field: optional numen.v1.Refusal refusal = 2;
   */
  refusal?: Refusal | undefined;
};

/**
 * Describes the message numen.v1.WriteSettingsFileResponse.
 * Use `create(WriteSettingsFileResponseSchema)` to create a new message.
 */
export const WriteSettingsFileResponseSchema: GenMessage<WriteSettingsFileResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_settings, 9);

/**
 * Presence is what a model's files are on this machine. It says where files
 * stand and nothing else: it is no reason to prefer one model to another.
 *
 * @generated from enum numen.v1.Presence
 */
export enum Presence {
  /**
   * Nothing was said about this model's files.
   *
   * @generated from enum value: PRESENCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The files stand where a fetch puts them.
   *
   * @generated from enum value: PRESENCE_PRESENT = 1;
   */
  PRESENT = 1,

  /**
   * The files are not on this machine. They are fetched when the model is next
   * needed.
   *
   * @generated from enum value: PRESENCE_NOT_FETCHED = 2;
   */
  NOT_FETCHED = 2,

  /**
   * The model is reached over the network, and nothing of it is fetched.
   *
   * @generated from enum value: PRESENCE_NOTHING_TO_FETCH = 3;
   */
  NOTHING_TO_FETCH = 3,
}

/**
 * Describes the enum numen.v1.Presence.
 */
export const PresenceSchema: GenEnum<Presence> = /*@__PURE__*/
  enumDesc(file_numen_v1_settings, 0);

/**
 * SettingsService answers about that file, one setting at a time and whole.
 *
 * @generated from service numen.v1.SettingsService
 */
export const SettingsService: GenService<{
  /**
   * Settings is every setting of the file, and the models the settings that
   * name one can be set to.
   *
   * @generated from rpc numen.v1.SettingsService.Settings
   */
  settings: {
    methodKind: "unary";
    input: typeof SettingsRequestSchema;
    output: typeof SettingsResponseSchema;
  },
  /**
   * ChooseSettings writes settings into that file. The file is patched as an
   * object, so every key a person typed stays where it was, and a file the
   * settings could not be read out of again is not written at all.
   *
   * @generated from rpc numen.v1.SettingsService.ChooseSettings
   */
  chooseSettings: {
    methodKind: "unary";
    input: typeof ChooseSettingsRequestSchema;
    output: typeof ChooseSettingsResponseSchema;
  },
  /**
   * SettingsFile is that file as its person wrote it, byte for byte.
   *
   * @generated from rpc numen.v1.SettingsService.SettingsFile
   */
  settingsFile: {
    methodKind: "unary";
    input: typeof SettingsFileRequestSchema;
    output: typeof SettingsFileResponseSchema;
  },
  /**
   * WriteSettingsFile replaces that file whole, with the bytes as they were
   * typed. A file the settings cannot be read out of is refused and the file is
   * left as it was; what is said names where in the file the trouble is. A file
   * standing at anything other than what the caller presents is left alone and
   * refused `stale`.
   *
   * @generated from rpc numen.v1.SettingsService.WriteSettingsFile
   */
  writeSettingsFile: {
    methodKind: "unary";
    input: typeof WriteSettingsFileRequestSchema;
    output: typeof WriteSettingsFileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_numen_v1_settings, 0);

