// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file numen/v1/theme.proto (package numen.v1, syntax proto3)
/* eslint-disable */

// What a client may ask about the themes it can wear.
//
// A theme is one stylesheet that redeclares the tokens the interface draws
// with. Nothing here reads inside one: what travels is its name, the text of
// its file, and which of them is chosen.

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file numen/v1/theme.proto.
 */
export const file_numen_v1_theme: GenFile = /*@__PURE__*/
  fileDesc("ChRudW1lbi92MS90aGVtZS5wcm90bxIIbnVtZW4udjEiVAoFVGhlbWUSDAoEbmFtZRgBIAEoCRINCgV0aXRsZRgCIAEoCRIeCgVzaGVsZhgDIAEoDjIPLm51bWVuLnYxLlNoZWxmEg4KBnBpbm5lZBgEIAEoCCIPCg1UaGVtZXNSZXF1ZXN0ImAKDlRoZW1lc1Jlc3BvbnNlEh8KBnRoZW1lcxgBIAMoCzIPLm51bWVuLnYxLlRoZW1lEg8KB2FwcGxpZWQYAiABKAkSHAoEbW9kZRgDIAEoDjIOLm51bWVuLnYxLk1vZGUiHAoMVGhlbWVSZXF1ZXN0EgwKBG5hbWUYASABKAkiHAoNVGhlbWVSZXNwb25zZRILCgNjc3MYASABKAkiOwoNQ2hvb3NlUmVxdWVzdBIMCgRuYW1lGAEgASgJEhwKBG1vZGUYAiABKA4yDi5udW1lbi52MS5Nb2RlIiAKDkNob29zZVJlc3BvbnNlEg4KBmZhaWxlZBgBIAEoCSIQCg5DaGFuZ2VkUmVxdWVzdCIgCg9DaGFuZ2VkUmVzcG9uc2USDQoFbmFtZXMYASADKAkqQAoFU2hlbGYSFQoRU0hFTEZfVU5TUEVDSUZJRUQQABIQCgxTSEVMRl9QUkVTRVQQARIOCgpTSEVMRl9NSU5FEAIqTAoETW9kZRIUChBNT0RFX1VOU1BFQ0lGSUVEEAASDwoLTU9ERV9TWVNURU0QARIOCgpNT0RFX0xJR0hUEAISDQoJTU9ERV9EQVJLEAMyhAIKDFRoZW1lU2VydmljZRI7CgZUaGVtZXMSFy5udW1lbi52MS5UaGVtZXNSZXF1ZXN0GhgubnVtZW4udjEuVGhlbWVzUmVzcG9uc2USOAoFVGhlbWUSFi5udW1lbi52MS5UaGVtZVJlcXVlc3QaFy5udW1lbi52MS5UaGVtZVJlc3BvbnNlEjsKBkNob29zZRIXLm51bWVuLnYxLkNob29zZVJlcXVlc3QaGC5udW1lbi52MS5DaG9vc2VSZXNwb25zZRJACgdDaGFuZ2VkEhgubnVtZW4udjEuQ2hhbmdlZFJlcXVlc3QaGS5udW1lbi52MS5DaGFuZ2VkUmVzcG9uc2UwAUJJWkdnaXRodWIuY29tL2ppdmEtc3R1ZGlvL251bWVuL21vZHVsZXMvbGlicy9wcm90b2NvbC9nZW4vbnVtZW4vdjE7bnVtZW52MWIGcHJvdG8z");

/**
 * Theme is one theme as the list refers to it. Its text is asked for by the
 * name here.
 *
 * @generated from message numen.v1.Theme
 */
export type Theme = Message<"numen.v1.Theme"> & {
  /**
   * Name is the shelf and the filename, `preset:dracula` or `mine:dracula`,
   * and it is how the theme is asked for again.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Title is what the file is called, without the shelf.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: numen.v1.Shelf shelf = 3;
   */
  shelf: Shelf;

  /**
   * Set for a theme that declares `color-scheme` itself. Light and dark are
   * the theme's own, and the mode has nothing left to choose.
   *
   * @generated from field: bool pinned = 4;
   */
  pinned: boolean;
};

/**
 * Describes the message numen.v1.Theme.
 * Use `create(ThemeSchema)` to create a new message.
 */
export const ThemeSchema: GenMessage<Theme> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 0);

/**
 * @generated from message numen.v1.ThemesRequest
 */
export type ThemesRequest = Message<"numen.v1.ThemesRequest"> & {
};

/**
 * Describes the message numen.v1.ThemesRequest.
 * Use `create(ThemesRequestSchema)` to create a new message.
 */
export const ThemesRequestSchema: GenMessage<ThemesRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 1);

/**
 * @generated from message numen.v1.ThemesResponse
 */
export type ThemesResponse = Message<"numen.v1.ThemesResponse"> & {
  /**
   * Every theme, the shipped ones first and each shelf by name.
   *
   * @generated from field: repeated numen.v1.Theme themes = 1;
   */
  themes: Theme[];

  /**
   * The theme that is applied, by its name.
   *
   * @generated from field: string applied = 2;
   */
  applied: string;

  /**
   * Which half of a pair the tokens resolve to.
   *
   * @generated from field: numen.v1.Mode mode = 3;
   */
  mode: Mode;
};

/**
 * Describes the message numen.v1.ThemesResponse.
 * Use `create(ThemesResponseSchema)` to create a new message.
 */
export const ThemesResponseSchema: GenMessage<ThemesResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 2);

/**
 * @generated from message numen.v1.ThemeRequest
 */
export type ThemeRequest = Message<"numen.v1.ThemeRequest"> & {
  /**
   * The theme, by its name.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message numen.v1.ThemeRequest.
 * Use `create(ThemeRequestSchema)` to create a new message.
 */
export const ThemeRequestSchema: GenMessage<ThemeRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 3);

/**
 * @generated from message numen.v1.ThemeResponse
 */
export type ThemeResponse = Message<"numen.v1.ThemeResponse"> & {
  /**
   * The stylesheet, whole and as it is written. Empty for a name that matches
   * no theme.
   *
   * @generated from field: string css = 1;
   */
  css: string;
};

/**
 * Describes the message numen.v1.ThemeResponse.
 * Use `create(ThemeResponseSchema)` to create a new message.
 */
export const ThemeResponseSchema: GenMessage<ThemeResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 4);

/**
 * @generated from message numen.v1.ChooseRequest
 */
export type ChooseRequest = Message<"numen.v1.ChooseRequest"> & {
  /**
   * The theme to apply, by its name. A name matching no theme is refused and
   * the settings are left as they are.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Which half of a pair the tokens resolve to from now on.
   *
   * @generated from field: numen.v1.Mode mode = 2;
   */
  mode: Mode;
};

/**
 * Describes the message numen.v1.ChooseRequest.
 * Use `create(ChooseRequestSchema)` to create a new message.
 */
export const ChooseRequestSchema: GenMessage<ChooseRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 5);

/**
 * @generated from message numen.v1.ChooseResponse
 */
export type ChooseResponse = Message<"numen.v1.ChooseResponse"> & {
  /**
   * Why the settings were not written, when they were not.
   *
   * @generated from field: string failed = 1;
   */
  failed: string;
};

/**
 * Describes the message numen.v1.ChooseResponse.
 * Use `create(ChooseResponseSchema)` to create a new message.
 */
export const ChooseResponseSchema: GenMessage<ChooseResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 6);

/**
 * @generated from message numen.v1.ChangedRequest
 */
export type ChangedRequest = Message<"numen.v1.ChangedRequest"> & {
};

/**
 * Describes the message numen.v1.ChangedRequest.
 * Use `create(ChangedRequestSchema)` to create a new message.
 */
export const ChangedRequestSchema: GenMessage<ChangedRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 7);

/**
 * @generated from message numen.v1.ChangedResponse
 */
export type ChangedResponse = Message<"numen.v1.ChangedResponse"> & {
  /**
   * The themes that changed, by their name. A theme whose file is gone is
   * named here too: what changed about it is that it is gone.
   *
   * @generated from field: repeated string names = 1;
   */
  names: string[];
};

/**
 * Describes the message numen.v1.ChangedResponse.
 * Use `create(ChangedResponseSchema)` to create a new message.
 */
export const ChangedResponseSchema: GenMessage<ChangedResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_theme, 8);

/**
 * Shelf is where a theme came off: this application, or the person's themes
 * folder. A theme carries its shelf in its name, and two themes on different
 * shelves can share a filename.
 *
 * @generated from enum numen.v1.Shelf
 */
export enum Shelf {
  /**
   * @generated from enum value: SHELF_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Ships inside the application.
   *
   * @generated from enum value: SHELF_PRESET = 1;
   */
  PRESET = 1,

  /**
   * A `.css` file in the person's themes folder.
   *
   * @generated from enum value: SHELF_MINE = 2;
   */
  MINE = 2,
}

/**
 * Describes the enum numen.v1.Shelf.
 */
export const ShelfSchema: GenEnum<Shelf> = /*@__PURE__*/
  enumDesc(file_numen_v1_theme, 0);

/**
 * Mode is what chooses between the two halves of a `light-dark()` pair.
 *
 * @generated from enum numen.v1.Mode
 */
export enum Mode {
  /**
   * @generated from enum value: MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * What the operating system says.
   *
   * @generated from enum value: MODE_SYSTEM = 1;
   */
  SYSTEM = 1,

  /**
   * @generated from enum value: MODE_LIGHT = 2;
   */
  LIGHT = 2,

  /**
   * @generated from enum value: MODE_DARK = 3;
   */
  DARK = 3,
}

/**
 * Describes the enum numen.v1.Mode.
 */
export const ModeSchema: GenEnum<Mode> = /*@__PURE__*/
  enumDesc(file_numen_v1_theme, 1);

/**
 * ThemeService answers what themes there are, and is told which one is chosen.
 *
 * @generated from service numen.v1.ThemeService
 */
export const ThemeService: GenService<{
  /**
   * Themes is every theme there is — the ones this application ships and the
   * ones in the person's themes folder — and which of them is applied.
   *
   * @generated from rpc numen.v1.ThemeService.Themes
   */
  themes: {
    methodKind: "unary";
    input: typeof ThemesRequestSchema;
    output: typeof ThemesResponseSchema;
  },
  /**
   * Theme is the text of one theme's file, as the file stands when it is
   * asked for. It is asked once for each theme that is tried on, and again
   * when that theme's file changes.
   *
   * @generated from rpc numen.v1.ThemeService.Theme
   */
  theme: {
    methodKind: "unary";
    input: typeof ThemeRequestSchema;
    output: typeof ThemeResponseSchema;
  },
  /**
   * Choose writes the theme and the mode into the settings. The file is
   * patched as an object, so every key a person typed stays where it was.
   *
   * @generated from rpc numen.v1.ThemeService.Choose
   */
  choose: {
    methodKind: "unary";
    input: typeof ChooseRequestSchema;
    output: typeof ChooseResponseSchema;
  },
  /**
   * Changed reports the person's themes folder having changed, for as long as
   * the caller listens. It says which themes, and nothing about them: the
   * caller knows what it is showing and asks for what it needs.
   *
   * @generated from rpc numen.v1.ThemeService.Changed
   */
  changed: {
    methodKind: "server_streaming";
    input: typeof ChangedRequestSchema;
    output: typeof ChangedResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_numen_v1_theme, 0);

