// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file numen/v1/vault.proto (package numen.v1, syntax proto3)
/* eslint-disable */

// What a client may ask about the vault a window is showing, taken whole.
//
// What the vault is, what has changed in it, and where in it the person stands:
// the questions that are about the vault itself and not about anything filed in
// it. Its files are file.proto, its notes note.proto and its text search.proto.

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Stretch } from "./shared_pb.js";
import { file_numen_v1_shared } from "./shared_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file numen/v1/vault.proto.
 */
export const file_numen_v1_vault: GenFile = /*@__PURE__*/
  fileDesc("ChRudW1lbi92MS92YXVsdC5wcm90bxIIbnVtZW4udjEiDgoMU3RhdGVSZXF1ZXN0IvsBCg1TdGF0ZVJlc3BvbnNlEgwKBG5hbWUYASABKAkSDAoEcGF0aBgCIAEoCRINCgVyZWFkeRgEIAEoCBIOCgZmYWlsZWQYBSABKAkSEQoJdW53YXRjaGVkGAYgASgJEhMKC3VucmVhY2hhYmxlGBEgASgJEg4KBmNodW5rcxgHIAEoAxIQCghlbWJlZGRlZBgIIAEoAxIRCgllbWJlZGRpbmcYCiABKAhKBAgDEARKBAgJEApKBAgLEBFSBWJvb2tzUgpib29rc19yZWFkUgRidXN5UgdpbmRleGVkUghsZWFybmluZ1IEbWFkZVIFb3dpbmdSB3JlYWRpbmciEAoOQ2hhbmdlc1JlcXVlc3QiUQoPQ2hhbmdlc1Jlc3BvbnNlEg0KBXBhdGhzGAEgAygJEg4KBnJlbG9hZBgCIAEoCBIfCgdyZW5hbWVkGAMgAygLMg4ubnVtZW4udjEuV2VudCIgCgRXZW50EgwKBGZyb20YASABKAkSCgoCdG8YAiABKAkiDgoMRm9jdXNSZXF1ZXN0Il0KDUZvY3VzUmVzcG9uc2USDAoEcGF0aBgBIAEoCRINCgVzdGFydBgCIAEoBRIOCgZsZW5ndGgYAyABKAUSHwoEYWxzbxgEIAMoCzIRLm51bWVuLnYxLlN0cmV0Y2giPgoQQXR0ZW5kaW5nUmVxdWVzdBIbCgR0YWJzGAEgAygLMg0ubnVtZW4udjEuVGFiEg0KBWZyb250GAIgASgJIhMKEUF0dGVuZGluZ1Jlc3BvbnNlIlQKA1RhYhIKCgJpZBgBIAEoCRIMCgRraW5kGAIgASgJEgwKBHBhdGgYAyABKAkSDQoFdGl0bGUYBCABKAkSCgoCYXQYBSABKAUSCgoCb2YYBiABKAUyjAIKDFZhdWx0U2VydmljZRI4CgVTdGF0ZRIWLm51bWVuLnYxLlN0YXRlUmVxdWVzdBoXLm51bWVuLnYxLlN0YXRlUmVzcG9uc2USQAoHQ2hhbmdlcxIYLm51bWVuLnYxLkNoYW5nZXNSZXF1ZXN0GhkubnVtZW4udjEuQ2hhbmdlc1Jlc3BvbnNlMAESOgoFRm9jdXMSFi5udW1lbi52MS5Gb2N1c1JlcXVlc3QaFy5udW1lbi52MS5Gb2N1c1Jlc3BvbnNlMAESRAoJQXR0ZW5kaW5nEhoubnVtZW4udjEuQXR0ZW5kaW5nUmVxdWVzdBobLm51bWVuLnYxLkF0dGVuZGluZ1Jlc3BvbnNlQklaR2dpdGh1Yi5jb20vaml2YS1zdHVkaW8vbnVtZW4vbW9kdWxlcy9saWJzL3Byb3RvY29sL2dlbi9udW1lbi92MTtudW1lbnYxYgZwcm90bzM", [file_numen_v1_shared]);

/**
 * @generated from message numen.v1.StateRequest
 */
export type StateRequest = Message<"numen.v1.StateRequest"> & {
};

/**
 * Describes the message numen.v1.StateRequest.
 * Use `create(StateRequestSchema)` to create a new message.
 */
export const StateRequestSchema: GenMessage<StateRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 0);

/**
 * @generated from message numen.v1.StateResponse
 */
export type StateResponse = Message<"numen.v1.StateResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * Ready is set when the scan has finished.
   *
   * @generated from field: bool ready = 4;
   */
  ready: boolean;

  /**
   * Why the scan stopped, when it stopped for a reason. A vault that could
   * not be read is not an empty one.
   *
   * @generated from field: string failed = 5;
   */
  failed: string;

  /**
   * Why the vault is not being followed, when it is not. Changes will only
   * appear when something asks for them again.
   *
   * @generated from field: string unwatched = 6;
   */
  unwatched: string;

  /**
   * Why an agent cannot be reached, when one cannot. The window works and the
   * panel says this instead of answering.
   *
   * @generated from field: string unreachable = 17;
   */
  unreachable: string;

  /**
   * Chunks is how many spans of text the index holds, and embedded is how many
   * of those carry a vector. Cutting finishes long before embedding does, so
   * the pair is what says how far searching by meaning has got. Both are zero
   * for a vault nothing has cut yet.
   *
   * @generated from field: int64 chunks = 7;
   */
  chunks: bigint;

  /**
   * @generated from field: int64 embedded = 8;
   */
  embedded: bigint;

  /**
   * Embedding says whether anything is going to turn the chunks into vectors.
   * False for an installation with no model, where `embedded` stays where it is
   * and the vault is searched by its words.
   *
   * @generated from field: bool embedding = 10;
   */
  embedding: boolean;
};

/**
 * Describes the message numen.v1.StateResponse.
 * Use `create(StateResponseSchema)` to create a new message.
 */
export const StateResponseSchema: GenMessage<StateResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 1);

/**
 * @generated from message numen.v1.ChangesRequest
 */
export type ChangesRequest = Message<"numen.v1.ChangesRequest"> & {
};

/**
 * Describes the message numen.v1.ChangesRequest.
 * Use `create(ChangesRequestSchema)` to create a new message.
 */
export const ChangesRequestSchema: GenMessage<ChangesRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 2);

/**
 * @generated from message numen.v1.ChangesResponse
 */
export type ChangesResponse = Message<"numen.v1.ChangesResponse"> & {
  /**
   * Paths of the files that changed, notes and assets alike. One that was
   * removed is named here too: what changed about it is that it is gone.
   *
   * @generated from field: repeated string paths = 1;
   */
  paths: string[];

  /**
   * Set when the vault has to be read again rather than followed — more
   * changed at once than could be reported.
   *
   * @generated from field: bool reload = 2;
   */
  reload: boolean;

  /**
   * The notes that were renamed by this application, each by where it was and
   * where it now is. A client showing one of them follows it there.
   *
   * @generated from field: repeated numen.v1.Went renamed = 3;
   */
  renamed: Went[];
};

/**
 * Describes the message numen.v1.ChangesResponse.
 * Use `create(ChangesResponseSchema)` to create a new message.
 */
export const ChangesResponseSchema: GenMessage<ChangesResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 3);

/**
 * Went is a note that is no longer where it was. The bytes do not change on the
 * way, so this says nothing about what the note holds.
 *
 * @generated from message numen.v1.Went
 */
export type Went = Message<"numen.v1.Went"> & {
  /**
   * Where the note was filed.
   *
   * @generated from field: string from = 1;
   */
  from: string;

  /**
   * Where it is filed now.
   *
   * @generated from field: string to = 2;
   */
  to: string;
};

/**
 * Describes the message numen.v1.Went.
 * Use `create(WentSchema)` to create a new message.
 */
export const WentSchema: GenMessage<Went> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 4);

/**
 * @generated from message numen.v1.FocusRequest
 */
export type FocusRequest = Message<"numen.v1.FocusRequest"> & {
};

/**
 * Describes the message numen.v1.FocusRequest.
 * Use `create(FocusRequestSchema)` to create a new message.
 */
export const FocusRequestSchema: GenMessage<FocusRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 5);

/**
 * @generated from message numen.v1.FocusResponse
 */
export type FocusResponse = Message<"numen.v1.FocusResponse"> & {
  /**
   * The source to put in front of the person: a note to see the neighbourhood
   * from, or a document to open.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * Where in the text of that source to open, counted in bytes. A length of
   * zero names the source and no place inside it, which is what a note arrives
   * with.
   *
   * @generated from field: int32 start = 2;
   */
  start: number;

  /**
   * @generated from field: int32 length = 3;
   */
  length: number;

  /**
   * The other stretches of the same source worth seeing. The person is taken to
   * the stretch above, and these are shown where they fall.
   *
   * @generated from field: repeated numen.v1.Stretch also = 4;
   */
  also: Stretch[];
};

/**
 * Describes the message numen.v1.FocusResponse.
 * Use `create(FocusResponseSchema)` to create a new message.
 */
export const FocusResponseSchema: GenMessage<FocusResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 6);

/**
 * @generated from message numen.v1.AttendingRequest
 */
export type AttendingRequest = Message<"numen.v1.AttendingRequest"> & {
  /**
   * Every tab the window has open, in the order the person was last in them.
   *
   * @generated from field: repeated numen.v1.Tab tabs = 1;
   */
  tabs: Tab[];

  /**
   * Which of them the person is looking at, by its id. Empty where the window
   * has nothing open.
   *
   * @generated from field: string front = 2;
   */
  front: string;
};

/**
 * Describes the message numen.v1.AttendingRequest.
 * Use `create(AttendingRequestSchema)` to create a new message.
 */
export const AttendingRequestSchema: GenMessage<AttendingRequest> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 7);

/**
 * @generated from message numen.v1.AttendingResponse
 */
export type AttendingResponse = Message<"numen.v1.AttendingResponse"> & {
};

/**
 * Describes the message numen.v1.AttendingResponse.
 * Use `create(AttendingResponseSchema)` to create a new message.
 */
export const AttendingResponseSchema: GenMessage<AttendingResponse> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 8);

/**
 * A Tab is one tab of the window: what kind it is, and what it holds.
 *
 * The kind is the client's own word — a note, a document, a recording — and a
 * reader that does not know one knows a tab of that kind is open and no more.
 *
 * @generated from message numen.v1.Tab
 */
export type Tab = Message<"numen.v1.Tab"> & {
  /**
   * Id is what the window calls this tab, which the front is named by.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Kind is what sort of tab it is.
   *
   * @generated from field: string kind = 2;
   */
  kind: string;

  /**
   * Path is the file it holds, by the path the vault files it under, and empty
   * for a tab holding no file. A plex holds the note it stands on.
   *
   * @generated from field: string path = 3;
   */
  path: string;

  /**
   * Title is what the tab is called, as the person reads it.
   *
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * At is where in what it holds the person stands, and of is how much there
   * is of it, both counted in whatever that thing is measured in: a document
   * in pages, counted from one, and a recording in milliseconds, where at is
   * how much of it has been written down. Both zero is a tab that measures
   * nothing.
   *
   * @generated from field: int32 at = 5;
   */
  at: number;

  /**
   * @generated from field: int32 of = 6;
   */
  of: number;
};

/**
 * Describes the message numen.v1.Tab.
 * Use `create(TabSchema)` to create a new message.
 */
export const TabSchema: GenMessage<Tab> = /*@__PURE__*/
  messageDesc(file_numen_v1_vault, 9);

/**
 * VaultService answers what the one vault a client is looking at is, and what
 * the person is at in it.
 *
 * @generated from service numen.v1.VaultService
 */
export const VaultService: GenService<{
  /**
   * State is what the vault is and how far reading it has got.
   *
   * @generated from rpc numen.v1.VaultService.State
   */
  state: {
    methodKind: "unary";
    input: typeof StateRequestSchema;
    output: typeof StateResponseSchema;
  },
  /**
   * Changes reports the notes that changed on disk, for as long as the caller
   * listens. It says which notes, and nothing about them: the caller knows
   * what it is showing and asks for what it needs.
   *
   * @generated from rpc numen.v1.VaultService.Changes
   */
  changes: {
    methodKind: "server_streaming";
    input: typeof ChangesRequestSchema;
    output: typeof ChangesResponseSchema;
  },
  /**
   * Focus reports the places something else asked to be put in front of the
   * person — an agent working the vault beside them — for as long as the
   * caller listens. What travelling there looks like is the client's.
   *
   * @generated from rpc numen.v1.VaultService.Focus
   */
  focus: {
    methodKind: "server_streaming";
    input: typeof FocusRequestSchema;
    output: typeof FocusResponseSchema;
  },
  /**
   * Attending says what the person has open — every tab of the window, and
   * which of them is in front. The client says so again whenever any of it
   * changes, and an agent working the vault beside them reads what it last
   * said.
   *
   * @generated from rpc numen.v1.VaultService.Attending
   */
  attending: {
    methodKind: "unary";
    input: typeof AttendingRequestSchema;
    output: typeof AttendingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_numen_v1_vault, 0);

