/**
 * The drawing, taken from the code rather than from memory.
 *
 * One diagram per interface module, each collapsed to the folder a component
 * lives in. Nothing here decides anything: the rules are in rules.cjs and the
 * graph is what they see.
 */
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { COLLAPSE, config, depcruise, modules, root } from './modules.mjs'

const drawn = ({ name, at, sources, says }) => {
  const mermaid = execFileSync(
    depcruise,
    [
      '--config',
      config,
      '--output-type',
      'mermaid',
      // A folder of ours is a box and so is a package: what the drawing is of
      // is which folders reach which, and inside a package is nobody's shape.
      // A scope is tried before the bare folder, so `@numen/ui` is a box and
      // `@numen` is not; anything with a `?` in it the tool refuses to run.
      '--collapse',
      COLLAPSE,
      ...sources,
    ],
    { cwd: join(root, at), encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  ).trim()
  return `## ${name}\n\n${says}\n\n\`${at}\`\n\n\`\`\`mermaid\n${mermaid}\n\`\`\`\n`
}

const page = [
  '# What the interface modules depend on',
  '',
  'Generated by `make graph`; edit nothing here. Each diagram is one module, collapsed to the folder a component lives in. What holds the direction is `modules/tools/depgraph/rules.cjs`: apps → libs/ui, never back and never sideways.',
  '',
  ...modules.map(drawn),
].join('\n')

const out = join(root, 'docs/dependencies.md')
writeFileSync(out, page)
console.log(`wrote ${relative(root, out)}`)
