/**
 * The drawing, taken from the code rather than from memory.
 *
 * One diagram per interface module, each collapsed to the folder a component
 * lives in. Nothing here decides anything: the rules are in rules.cjs and the
 * graph is what they see.
 */
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { COLLAPSE, config, depcruise, modules, root } from './modules.mjs'

/**
 * The edges put in one order, whatever order they were found in.
 *
 * The cruiser emits them in the order it walked the disk, so two runs over one
 * tree draw the same graph with two spellings and the committed drawing reads
 * as drift. Every other line — the flowchart, the boxes, the nodes — keeps the
 * place it stands in, which is what makes the drawing readable.
 */
const ordered = (mermaid) => {
  const lines = mermaid.split('\n')
  const edge = /^\s*[A-Za-z0-9]+-->[A-Za-z0-9]+\s*$/
  const out = []
  for (let at = 0; at < lines.length; at += 1) {
    if (!edge.test(lines[at])) {
      out.push(lines[at])
      continue
    }
    const from = at
    while (at < lines.length && edge.test(lines[at])) at += 1
    out.push(...lines.slice(from, at).sort())
    at -= 1
  }
  return out.join('\n')
}

/**
 * The drawing without the climb out of the module.
 *
 * Everything a module reaches but its own files stands above it — the packages
 * at the source root the install hoists to, the corpora in the schema — so the
 * reporter opens a box for each `..` on the way up. How far up a thing sits is
 * where the module happens to stand in the tree, and the box that names it is
 * the next one in.
 */
const inward = (mermaid) => {
  const climb = /^subgraph\s+[A-Za-z0-9]+\["\.\."\]$/
  const dropped = []
  const out = []
  for (const line of mermaid.split('\n')) {
    if (line.startsWith('subgraph ')) {
      dropped.push(climb.test(line))
      if (dropped.at(-1)) continue
    } else if (line === 'end' && dropped.pop()) continue
    out.push(line)
  }
  return out.join('\n')
}

const drawn = ({ name, at, sources, says }) => {
  const mermaid = execFileSync(
    depcruise,
    [
      '--config',
      config,
      '--output-type',
      'mermaid',
      // A folder of ours is a box and so is a package: what the drawing is of
      // is which folders reach which, and inside a package is nobody's shape.
      // A scope is tried before the bare folder, so `@numen/ui` is a box and
      // `@numen` is not; anything with a `?` in it the tool refuses to run.
      '--collapse',
      COLLAPSE,
      ...sources,
    ],
    { cwd: join(root, at), encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  ).trim()
  return `## ${name}\n\n${says}\n\n\`${at}\`\n\n\`\`\`mermaid\n${ordered(inward(mermaid))}\n\`\`\`\n`
}

const page = [
  '# What the interface modules depend on',
  '',
  'Generated by `make graph`; edit nothing here. Each diagram is one module, collapsed to the folder a component lives in. What holds the direction is `modules/tools/depgraph/rules.cjs`: apps → libs/ui, never back and never sideways.',
  '',
  ...modules.map(drawn),
].join('\n')

const out = join(root, 'docs/dependencies.md')
writeFileSync(out, page)
console.log(`wrote ${relative(root, out)}`)
