/**
 * The icon drawn beside a command wherever it is offered. A command has one
 * icon, from Lucide, so both menus draw the same thing for the same thing.
 *
 * A command is named here by the identity it carries in `commands.ts` and in
 * what each tab does itself.
 */
import {
  ALargeSmall,
  ArrowRightLeft,
  Bot,
  Captions,
  CaptionsOff,
  Command,
  Compass,
  Contrast,
  Copy,
  CornerDownRight,
  CornerLeftUp,
  FilePlus,
  FileText,
  FolderOpen,
  FolderPlus,
  FolderRoot,
  FolderTree,
  Gauge,
  Globe,
  HardDriveDownload,
  Layers,
  LayoutTemplate,
  ListTree,
  Navigation,
  Palette,
  PenLine,
  Plus,
  RefreshCw,
  Rows3,
  Ruler,
  ScanText,
  Search,
  SlidersHorizontal,
  SpellCheck,
  SquareX,
  Trash2,
  Type,
  Waypoints,
  X,
  type LucideIcon,
} from '@lucide/vue'

/** What each command is drawn as. A map, so an identity answers for itself. */
const ICONS: ReadonlyMap<string, LucideIcon> = new Map([
  ['read', FileText],
  ['beside', FileText],
  ['travel', Waypoints],
  ['child', CornerDownRight],
  ['parent', CornerLeftUp],
  ['jump', ArrowRightLeft],
  ['title', Type],
  ['ask', Bot],
  ['copy', Copy],
  ['reveal', FolderOpen],
  ['preset', Gauge],
  ['remove', Trash2],
  ['destroy', Trash2],
  ['transcribe', Captions],
  ['proofread', SpellCheck],
  ['recognise', ScanText],
  ['downloadText', RefreshCw],
  ['downloadCopy', HardDriveDownload],
  ['deleteText', CaptionsOff],
  ['deleteCopy', Trash2],
  ['newNote', FilePlus],
  ['newDeck', Layers],
  ['newStencil', LayoutTemplate],
  ['newPreset', Gauge],
  ['importUrl', Globe],
  ['newFolder', FolderPlus],
  ['rename', PenLine],
  ['note', FilePlus],
  ['deck', Layers],
  ['stencil', LayoutTemplate],
  ['plex', Waypoints],
  ['agent', Bot],
  ['files', FolderTree],
  ['find', Search],
  ['commands', Command],
  ['close', SquareX],
  ['appearance', Palette],
  ['mode', Contrast],
  ['interfaceScale', Ruler],
  ['textScale', ALargeSmall],
  ['syncing', RefreshCw],
  ['hanging', ListTree],
  ['parts', Rows3],
  ['settings', SlidersHorizontal],
  ['first', Compass],
  ['goto', Navigation],
  ['openVault', FolderRoot],
  ['newVault', Plus],
  ['renameVault', PenLine],
  ['forgetVault', X],
  ['eraseVault', Trash2],
])

/** The icon for a command, and nothing where it has none. */
export const iconFor = (id: string): LucideIcon | null => ICONS.get(id) ?? null
