/** What the settings file holds, and how the window is drawn from it. */
export { DESIGNED, isInBounds, ladder, MODES, NOWHERE, parseSize, SCHEMES } from './lib/appearance'
export type { Configuration, Model, Presence, SettingEdit } from './lib/configuration'
export { DEFAULT_PARTS, ladder as hangingLadder } from './lib/hanging'
export type { HangingSettings } from './lib/hanging'
export { DEFAULT_STARTS, createReviewSetting } from './model/review'
export type { ReviewSettings } from './model/review'
export { getSettingAt, createSettingsStore } from './model/store'
export { themes } from './api/theme'
export type { Appearance, Bounds, Mode, Ranges, Scales, Sizes, Theme, Themes } from './api/theme'
export { write } from './lib/write'
