/** The tags a card is drawn with. */
export const DRAWN = new Set([
  'p',
  'br',
  'hr',
  'span',
  'div',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'strong',
  'b',
  'em',
  'i',
  'u',
  's',
  'del',
  'ins',
  'mark',
  'small',
  'sub',
  'sup',
  'code',
  'pre',
  'kbd',
  'samp',
  'var',
  'abbr',
  'q',
  'cite',
  'dfn',
  'time',
  'bdi',
  'bdo',
  'ruby',
  'rt',
  'rp',
  'blockquote',
  'ul',
  'ol',
  'li',
  'dl',
  'dt',
  'dd',
  'table',
  'thead',
  'tbody',
  'tfoot',
  'tr',
  'th',
  'td',
  'caption',
  'colgroup',
  'col',
  'a',
  'img',
  'figure',
  'figcaption',
])

/** The tags that go, and everything they hold with them. */
export const STRUCK = new Set([
  'script',
  'style',
  'iframe',
  'object',
  'embed',
  'noscript',
  'template',
  'svg',
  'math',
  'link',
  'meta',
  'base',
  'form',
  'input',
  'button',
  'textarea',
  'select',
  'option',
  'head',
  'title',
  'frame',
  'frameset',
  'applet',
  'canvas',
  'audio',
  'video',
  'source',
  'track',
  'portal',
])

/** The attributes any tag may carry. */
export const ANY = new Set(['dir', 'lang', 'title'])

/** What each tag may carry beyond those. */
export const OWN: Readonly<Record<string, readonly string[]>> = {
  a: ['href'],
  img: ['src', 'alt', 'width', 'height'],
  td: ['colspan', 'rowspan'],
  th: ['colspan', 'rowspan', 'scope'],
  ol: ['start', 'reversed'],
  time: ['datetime'],
  col: ['span'],
  colgroup: ['span'],
}

/** The schemes a link may point at. */
export const SCHEMES = new Set(['http:', 'https:', 'mailto:', 'tel:'])

/** The declarations a tag may be styled with. */
export const STYLED = new Set([
  'color',
  'background-color',
  'font-family',
  'font-size',
  'font-style',
  'font-weight',
  'text-align',
  'text-decoration',
  'vertical-align',
])
